research_industry_task:
  description: >
    Conduct comprehensive research to understand "{company}"'s industry and operations. Investigate: - Industry category and market segment - Key products, services, and value propositions - Strategic priorities and company vision

    Use this to establish foundational context for further analysis.
  expected_output: >
    A well-organized report containing: - Industry overview - Market segment and position - Key offerings and strategic themes - Source references
  agent: industry_researcher

identify_top_competitors_task:
  description: >
    Based on the industry research, identify the top 3 direct competitors to "{company}". Justify each selection by analyzing: - Market overlap - Product or service similarities - Shared customer segments

    Provide links and references for each.
  expected_output: >
    A list of 3 direct competitors with: - Justification for inclusion - Summary of overlap - Source references
  agent: competitor_researcher

analyze_competitor_ai_strategy_task:
  description: >
    Analyze how the 3 identified competitors of "{company}" are using AI/ML/GenAI. For each, research: - Specific AI/ML/GenAI initiatives or tools - The business problem they solved - KPIs or metrics improved - Estimated ROI or impact (if available)
  expected_output: >
    A matrix or structured list with one section per competitor including: - Overview of AI initiatives - Business context - Technology stack (if known) - Outcomes achieved
  agent: competitor_researcher

write_competitor_impact_articles_task:
  description: >
    Write 2-3 blog-style articles per competitor, based on their AI/ML/GenAI strategy. Each article should: - Highlight a single use case - Include problem, AI solution, and measurable results - Propose how "{company}" could adapt or enhance the idea

    Use Markdown with H2/H3 headers and anchors for ToC linking.
  expected_output: >
    A Markdown file with 6-9 articles in this format: ## [Competitor Name]: [Use Case Title] ### Problem ### Solution ### Results ### How "{company}" Can Apply It
  agent: impact_writer

propose_ai_use_cases_task:
  description: >
    Propose 10 AI/ML/GenAI use cases specifically for "{company}" based on industry trends and successful competitor strategies. Focus on: - Operational improvement - Customer experience - Innovation alignment

    Include article references if available.
  expected_output: >
    A list of 10 proposed use cases each with: - Title - Description - Business Objective - AI Technology Used - Expected Impact - Cross-functional Benefits - Related article link (if applicable)
  agent: use_case_analyst

compile_final_proposal_task:
  description: >
    Create a polished Markdown document summarizing all findings for "{company}": - Industry research - Top competitors and their AI strategies - Impact articles (as written) - Proposed AI/ML/GenAI use cases

    The doc should be: - Cleanly formatted using Markdown (##, ###) - Include anchor-based ToC - Segmented by section with links where applicable
  expected_output: >
    A client-ready Markdown document with: - Title & Introduction - Table of Contents (anchor-linked) - Industry Summary - Competitor Overview - Blog-style Articles - Use Case Table (Markdown format)
  output_file: proposal.md
  agent: proposal_writer
