import streamlit as st
import os
import time
from dotenv import load_dotenv
from crew import research_crew

# Load environment variables
load_dotenv()


def check_api_keys():
    required_vars = ['SERPER_API_KEY', 'OPENROUTER_API_KEY']
    missing_vars = [var for var in required_vars if not os.getenv(var)]
    return missing_vars


def main():
    st.set_page_config(
        page_title="🔬 Strategic AI Research Assistant",
        page_icon="🧠",
        layout="wide"
    )

    st.title("🔬 Strategic AI Research Assistant")
    st.markdown("*Powered by CrewAI + Streamlit*")

    # Session state setup
    if 'research_completed' not in st.session_state:
        st.session_state.research_completed = False
    if 'research_result' not in st.session_state:
        st.session_state.research_result = None
    if 'research_error' not in st.session_state:
        st.session_state.research_error = None

    # Sidebar
    with st.sidebar:
        st.header("⚙️ Configuration")
        missing_vars = check_api_keys()

        if missing_vars:
            st.error("❌ Missing API Keys")
            for var in missing_vars:
                st.code(f"{var}=your_api_key_here")
        else:
            st.success("✅ All API Keys Configured")

        st.header("🧠 Multi-Agent Team")
        st.markdown("""
        - 🔍 **Industry Researcher**
        - 🧠 **Competitor Analyst**
        - ✍️ **Proposal Writer**
        """)

    # Input
    st.header("🏢 Enter Company Name for AI Research")
    company = st.text_input("Company Name", placeholder="e.g., BNY Mellon")

    if st.button("🚀 Run Research", type="primary", disabled=bool(missing_vars)):
        if not company.strip():
            st.error("Please enter a valid company name")
        else:
            st.session_state.research_completed = False
            st.session_state.research_result = None
            st.session_state.research_error = None

            with st.container():
                st.info("🔄 Running CrewAI Agents...")
                progress = st.progress(0)
                for i in range(101):
                    progress.progress(i)
                    time.sleep(0.02)

            try:
                result = research_crew.kickoff({"company": company})
                st.session_state.research_result = result
                st.session_state.research_completed = True
                st.session_state.research_error = None
            except Exception as e:
                st.session_state.research_error = str(e)
                st.session_state.research_completed = True

    # Results
    if st.session_state.research_completed:
        st.header("📄 Final Proposal")

        if st.session_state.research_error:
            st.error(f"❌ Error occurred: {st.session_state.research_error}")
        else:
            filepath = "proposal.md"
            if os.path.exists(filepath):
                with open(filepath, 'r', encoding='utf-8') as f:
                    content = f.read()

                st.markdown("✅ **Final output generated by the Crew:**")
                st.markdown(content)

                st.download_button(
                    label="📥 Download Proposal",
                    data=content,
                    file_name="proposal.md",
                    mime="text/markdown"
                )
            else:
                st.warning("⚠️ Final proposal file not found.")

    st.markdown("---")
    st.markdown("*Built with ❤️ using CrewAI, Streamlit, and OpenRouter LLMs*")


if __name__ == "__main__":
    main()
